version: 2


references:
  workspace_root: &workspace_root
    /home/circleci/project

  node_image: &node_image
    circleci/node:9.9

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root


  node_config: &node_config
    docker:
      - image: *node_image
    working_directory: *workspace_root

  gcloud_sdk_config: &gcloud_sdk_config
    docker:
      - image: google/cloud-sdk:190.0.1
    working_directory: *workspace_root

  activate_gcloud_sdk: &activate_gcloud_sdk
    run:
      name: activate gcloud sdk
      command: |
        echo $GC_JSON_KEY_FILE >> secret.json
        CLOUDSDK_PYTHON_SITEPACKAGES=1 gcloud auth activate-service-account --key-file secret.json

  yarn_cache_restore: &yarn_cache_restore
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

  yarn_install: &yarn_install
    run: yarn install --prefer-offline --frozen-lockfile

  yarn_cache_save: &yarn_cache_save
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test-build:
    <<: *node_config
    steps:
      - checkout

      - run:
          name: install chrome headless dependencies
          command: |
            sudo apt-get update

            sudo apt-get install -yq --no-install-recommends libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
            # libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            # libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            # libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
            # libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
            # libnss3

      - run:
          name: install api
          working_directory: packages/api
          command: |
            yarn install

      - run:
          name: install app
          working_directory: packages/app
          command: |
            yarn install

      - run:
          name: install ssr
          working_directory: packages/ssr
          command: |
            yarn install

      - run:
          name: install image renderer
          working_directory: packages/image-renderer
          command: |
            yarn install

      - run:
          name: build app
          working_directory: packages/app
          command: |
            yarn build

      - run:
          name: test
          command: __tests__/run.sh

      - run:
          name: build api
          working_directory: packages/api
          command: |
            yarn build

      - run:
          name: build ssr
          working_directory: packages/ssr
          command: |
            yarn build

      - run:
          name: build static pages
          working_directory: packages/ssr
          command: |
            yarn build:staticPage
            mv dist/* ../app/dist/

      - run:
          name: render image
          working_directory: packages/image-renderer
          command: |
            yarn render:all
            mv dist/* ../app/dist/


      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/ssr/lib
            - packages/ssr/packages.json
            - packages/api/lib
            - packages/api/packages.json
            - packages/app/dist

      - store_artifacts:
          path: packages/app/dist

  deploy-asset:
    <<: *gcloud_sdk_config
    steps:
      - *activate_gcloud_sdk
      - *attach_workspace
      - run:
          name: publish into bucket
          working_directory: packages/app
          command: |
            # create the bucket
            # gsutil mb -c STANDARD -l EUROPE-WEST1 -p $GC_PROJECT gs://$BUCKET || echo 1

            # sync the folder dist with the bucket ( options -d is for removing from the bucket )
            gsutil -m rsync -r dist gs://$BUCKET

            # use gzip with this files
            gsutil -m cp -r -z html,css,js,xml,txt,json,map,svg dist/* gs://$BUCKET

            # set the bucket accessibility
            gsutil -m acl set -R -a public-read gs://$BUCKET

            # set the bucket index and 404 files
            gsutil web set -m index.html -e index.html gs://$BUCKET

            # set headers for security purpose
            # will fail : can only set a restricted set of headers
            # gsutil setmeta -h "x-frame-options:SAMEORIGIN" gs://$BUCKET/index.html

  deploy-microservices:
    <<: *node_config
    steps:
      - *attach_workspace

      - run: npm install -g now

      - run: now --token $NOW_TOKEN

      - run:
          working_directory: packages/api
          command: yarn deploy

      - run:
          working_directory: packages/ssr
          command: yarn deploy


workflows:
  version: 2
  build-deploy:
    jobs:
      - test-build
      - deploy-asset:
          requires:
            - test-build
      - deploy-microservices:
          requires:
            - test-build
